mutation (
  $environment: Int
  $name: String!
  $command: String
  $service: String!
  $description: String!
  $confirmationText: String
  $permission: TaskPermission
  $systemWide: Boolean
) {
  addAdvancedTaskDefinition(input: {
    environment: $environment
    command: $command
    name: $name
    service: $service
    type: COMMAND
    description: $description
    confirmationText: $confirmationText
    permission: $permission
    systemWide: $systemWide
    projectKeyInjection: true
  }) {
    ... on AdvancedTaskDefinitionCommand {
      id
    }
  }
}
