query (
  $id: Int!
){
  environmentById(
    id: $id,
  ){
    id
    name
    route
    routes
    deployType
    environmentType
    openshiftProjectName
    autoIdle
    deployTitle
    deployBaseRef
    deployHeadRef
    updated
    created
    deleted
    openshift {
        id
        name
        created
        cloudRegion
        cloudProvider
        friendlyName
        sshHost
        sshPort
        routerPattern
        buildImage
    }
    services{
      id
      name
      type
      containers{
        name
        volumemounts{
          name
          path
        }
        ports{
          name
          port
        }
      }
      created
      updated
      abandoned
    }
    volumes{
      id
      name
      type
      storageType
      kibRequested
      created
      updated
      abandoned
    }
  }
}
