mutation (
    $id: Int!
    $patch: UpdateEnvironmentPatchInput!){
    updateEnvironment(
        input: {
            id: $id
            patch: $patch
        }
    ){
        id
        name
        route
        routes
        deployType
        environmentType
        openshiftProjectName
        updated
        created
        deleted
        services{
            id
            name
            type
            containers{
                name
                volumes{
                    name
                    path
                }
                ports{
                    name
                    port
                }
            }
            created
            updated
            abandoned
        }
        volumes{
            id
            name
            type
            storageType
            size
            created
            updated
            abandoned
        }
    }
}