package schema

type RouteSource string

const (
	APIRoute           RouteSource = "API"
	YAMLRoute          RouteSource = "YAML"
	AutogeneratedRoute RouteSource = "AUTOGENERATED"
)

type RouteType string

const (
	StandardRoute RouteType = "STANDARD"
	ActiveRoute   RouteType = "ACTIVE"
	StandbyRoute  RouteType = "STANDBY"
)

type RouteInsecure string

const (
	InsecureAllow    RouteInsecure = "Allow"
	InsecureRedirect RouteInsecure = "Redirect"
	InsecureNone     RouteInsecure = "None"
)

type AlternativeName struct {
	ID     uint   `json:"id,omitempty"`
	Domain string `json:"domain"`
}

type RouteAnnotation struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PathRoute struct {
	ID        uint   `json:"id,omitempty"`
	ToService string `json:"toService"`
	Path      string `json:"path"`
}

type AutogeneratedPathRoute struct {
	ID          uint   `json:"id,omitempty"`
	ToService   string `json:"toService"`
	FromService string `json:"fromService"`
	Path        string `json:"path"`
}

// Route is the Lagoon API Route object.
type Route struct {
	ID                         uint              `json:"id,omitempty"`
	Project                    *Project          `json:"project,omitempty"`
	Environment                *Environment      `json:"environment,omitempty"`
	Domain                     string            `json:"domain"`
	Service                    string            `json:"service"`
	Updated                    string            `json:"updated,omitempty"`
	Created                    string            `json:"created,omitempty"`
	TLSAcme                    bool              `json:"tlsAcme"`
	Insecure                   RouteInsecure     `json:"insecure"`
	Annotations                []RouteAnnotation `json:"annotations,omitempty"`
	PathRoutes                 []PathRoute       `json:"pathRoutes,omitempty"`
	Primary                    bool              `json:"primary"`
	AlternativeNames           []AlternativeName `json:"alternativeNames,omitempty"`
	Source                     RouteSource       `json:"source"`
	Type                       RouteType         `json:"type"`
	DisableRequestVerification bool              `json:"disableRequestVerification"`
	HSTSEnabled                bool              `json:"hstsEnabled"`
	HSTSPreload                bool              `json:"hstsPreload"`
	HSTSIncludeSubdomains      bool              `json:"hstsIncludeSubdomains"`
	HSTSMaxAge                 uint              `json:"hstsMaxAge,omitempty"`
}

type AutogeneratedRouteConfig struct {
	Updated                    string                   `json:"updated,omitempty"`
	Enabled                    bool                     `json:"enabled"`
	AllowPullRequests          bool                     `json:"allowPullRequests"`
	Prefixes                   []string                 `json:"prefixes"`
	PathRoutes                 []AutogeneratedPathRoute `json:"pathRoutes,omitempty"`
	DisableRequestVerification bool                     `json:"disableRequestVerification"`
	Insecure                   RouteInsecure            `json:"insecure"`
	TLSAcme                    bool                     `json:"tlsAcme"`
}
